### ISSUE TITLE
Could you create step by step video for youtube ? 

### ISSUE THREAD

**Issue by patryk-siewiera** [digitalec/thinkmac-t470#2]

**Comment by digitalec** [comment]
I don’t think it would be much value. There’s nothing unique in the way this is done just the customized collection of the files to get it working.

If you’re using the same model just use my EFI folder but remove or rename the DSDT.aml file. You can use the guide I posted to patch yours.

Are you stuck on something specific? I’m happy to help if you’re stuck on something.

**Comment by digitalec** [comment]
No response, closing issue. If you need help getting a specific device working, please open a new issue.
