### ISSUE TITLE
restart after progress bar loading

### ISSUE THREAD

**Issue by HadesLei1217** [digitalec/thinkmac-t470#4]
During installation, restart after progress bar loading,Will restart indefinitely,Can you help me?
thank you.
My machine configuration:
thinkpad t470
bios 1.
i5-6200U @ 2.30GHz
20JMA00ECD ( 6th/7th Generation Intel Processor Family I/O - 9D48  )

**Comment by digitalec** [comment]
That's a different chip than I have so you may need a different config.plist. Can you boot with verbose enabled and post a picture? Also, what graphics chip does your model have?

**Comment by HadesLei1217** [comment]
Graphics chip is Intel HD Graphics 520.I'll send you a boot picture later. Thank you

**Comment by HadesLei1217** [comment]
![boot_error](https://user-images.githubusercontent.com/53035376/82626996-d03e1100-9c1b-11ea-8b0a-56e1e4841bbf.png)
This is boot log picture.

**Comment by digitalec** [comment]
Make sure you move/rename my DSDT file under ACPI. I included it for reference but should’ve renamed it.

If you’re using my patched DSDT you’ll have ACPI errors which is what your screenshot shows.

**Comment by HadesLei1217** [comment]
I see,I thought the same machine could be modified.Think you.

**Comment by digitalec** [comment]
This should work on your system but you’ll have to dump your own ACPI files from the CLOVER boot menu and patch them with the patches your specific system requires.

My DSDT may not even work on my system if I change some hardware or upgrade/alter the UEFI settings. Feel free to open another issue if you’re still stuck.

**Comment by digitalec** [comment]
Resolved in commit b82ab9a9
